name: Run RateUp Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Updated to use Node.js 20

    - name: Set up Python
      uses: actions/setup-python@v4 # Updated to use Node.js 20
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the script
      run: python rate_up.py
